# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/n880s/extract-files.sh - DO NOT EDIT

# All the blobs necessary for n880s
PRODUCT_COPY_FILES += \
    vendor/zte/n880s/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/n880s/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/n880s/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/n880s/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/n880s/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/zte/n880s/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/n880s/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/n880s/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/n880s/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/zte/n880s/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/zte/n880s/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/n880s/proprietary/lib/hw/copybit.blade.so:system/lib/hw/copybit.n880s.so \
    vendor/zte/n880s/proprietary/lib/hw/gralloc.blade.so:system/lib/hw/gralloc.n880s.so \
    vendor/zte/n880s/proprietary/lib/hw/lights.blade.so:system/lib/hw/lights.n880s.so \
    vendor/zte/n880s/proprietary/lib/hw/sensors.blade.so:system/lib/hw/sensors.n880s.so \
    vendor/zte/n880s/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/zte/n880s/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/n880s/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/zte/n880s/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/zte/n880s/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/zte/n880s/proprietary/etc/init.wlanprop.sh:system/etc/init.wlanprop.sh \
    vendor/zte/n880s/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/n880s/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/zte/n880s/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/zte/n880s/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/zte/n880s/proprietary/libdll.so:system/lib/libdll.so \
    vendor/zte/n880s/proprietary/libcm.so:system/lib/libcm.so \
    vendor/zte/n880s/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/n880s/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/n880s/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/n880s/proprietary/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/zte/n880s/proprietary/libwms.so:system/lib/libwms.so \
    vendor/zte/n880s/proprietary/libnv.so:system/lib/libnv.so \
    vendor/zte/n880s/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/n880s/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/n880s/proprietary/libdss.so:system/lib/libdss.so \
    vendor/zte/n880s/proprietary/libauth.so:system/lib/libauth.so \
    vendor/zte/n880s/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/n880s/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/zte/n880s/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/n880s/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/n880s/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/n880s/proprietary/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/zte/n880s/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/zte/n880s/proprietary/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/zte/n880s/proprietary/libOmxQcelpDec.so:/system/lib/libOmxQcelpDec.so \
    vendor/zte/n880s/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/zte/n880s/proprietary/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/zte/n880s/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/zte/n880s/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/zte/n880s/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/zte/n880s/proprietary/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/zte/n880s/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/zte/n880s/proprietary/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/zte/n880s/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/zte/n880s/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/zte/n880s/proprietary/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/zte/n880s/proprietary/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/zte/n880s/proprietary/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/zte/n880s/proprietary/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/zte/n880s/proprietary/libloc.so:system/lib/libloc.so \
    vendor/zte/n880s/proprietary/libloc.so:obj/lib/libloc.so \
    vendor/zte/n880s/proprietary/libloc-rpc.so:system/lib/libloc-rpc.so \
    vendor/zte/n880s/proprietary/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/zte/n880s/proprietary/libreference-cdma-sms.so:system/lib/libreference-cdma-sms.so \
    vendor/zte/n880s/proprietary/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/zte/n880s/proprietary/libSimCardAuth.so:system/lib/libSimCardAuth.so \
    vendor/zte/n880s/proprietary/iwmulticall:system/xbin/iwmulticall \
    vendor/zte/n880s/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/zte/n880s/proprietary/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/zte/n880s/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/zte/n880s/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/zte/n880s/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/zte/n880s/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/zte/n880s/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so 

#    vendor/zte/n880s/proprietary/libaudiopolicy.so:system/lib/libaudiopolicy.so \
#    vendor/zte/n880s/proprietary/bin/sdptool:system/bin/sdptool \
#    vendor/zte/n880s/proprietary/bin/rild:system/bin/rild \
#    vendor/zte/n880s/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
#    vendor/zte/n880s/proprietary/bin/netd:system/bin/netd \
#    vendor/zte/n880s/proprietary/bin/pand:system/bin/pand \
#    vendor/zte/n880s/proprietary/bin/vold:system/bin/vold \

# added by ioz9 for fix CPU governer
PRODUCT_COPY_FILES += \
    vendor/zte/n880s/proprietary/etc/init.d/10cpu:system/etc/init.d/10cpu
