
# This file is generated by device/zte/roamer/extract-files.sh - DO NOT EDIT

# All the blobs necessary for the Skate

# Binary
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/roamer/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/zte/roamer/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/zte/roamer/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init

# Bluetooth
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/zte/roamer/proprietary/etc/BCM4329B1_002.002.023.0735.0754.hcd:system/etc/BCM4329B1_002.002.023.0735.0754.hcd \
    vendor/zte/roamer/proprietary/bin/hciattach:system/bin/hciattach

# Graphics
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/roamer/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/roamer/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/roamer/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/roamer/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/zte/roamer/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/roamer/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw 

# RIL
PRODUCT_COPY_FILES += \
   vendor/zte/roamer/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/roamer/proprietary/lib/libSimCardAuth.so:system/lib/libSimCardAuth.so \
   vendor/zte/roamer/proprietary/lib/cm.so:system/lib/cm.so \
    vendor/zte/roamer/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/roamer/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/roamer/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
    vendor/zte/roamer/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/zte/roamer/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    vendor/zte/roamer/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
    vendor/zte/roamer/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/roamer/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/roamer/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/zte/roamer/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/zte/roamer/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/zte/roamer/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/zte/roamer/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/roamer/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/roamer/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/roamer/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/zte/roamer/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/zte/roamer/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/roamer/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/roamer/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/zte/roamer/proprietary/lib/libauth.so:system/lib/libauth.so

# Camera
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/zte/roamer/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/zte/roamer/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/zte/roamer/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/zte/roamer/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/roamer/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/zte/roamer/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/roamer/proprietary/lib/libmmipl.so:system/lib/libmmipl.so

# OMX
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/lib/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/zte/roamer/proprietary/lib/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxQcelpDec.so:/system/lib/libOmxQcelpDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/zte/roamer/proprietary/lib/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/zte/roamer/proprietary/lib/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/zte/roamer/proprietary/lib/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/zte/roamer/proprietary/lib/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/zte/roamer/proprietary/lib/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/zte/roamer/proprietary/lib/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/zte/roamer/proprietary/lib/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/zte/roamer/proprietary/lib/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/zte/roamer/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/zte/roamer/proprietary/lib/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/zte/roamer/proprietary/bin/vold:system/bin/vold 
		
# GPS
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/zte/roamer/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/zte/roamer/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so

# wifi
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/zte/roamer/proprietary/bin/wl:system/bin/wl 	

# HW
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/zte/roamer/proprietary/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/zte/roamer/proprietary/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/zte/roamer/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so 
	
# Misc
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/zte/roamer/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so

# ril
PRODUCT_COPY_FILES += \
    vendor/zte/roamer/proprietary/lib/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/zte/roamer/proprietary/lib/libril.so:/system/lib/libril.so \
    vendor/zte/roamer/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/zte/roamer/proprietary/lib/libreference-cdma-sms.so:/system/lib/libreference-cdma-sms.so 
	
