# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/blade/extract-files.sh - DO NOT EDIT

# All the blobs necessary for blade
PRODUCT_COPY_FILES += \
    vendor/zte/blade/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/blade/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/blade/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/blade/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/blade/proprietary/libgsl.so:system/lib//libgsl.so \
    vendor/zte/blade/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/blade/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/blade/proprietary/qmuxd:system/bin/qmuxd \
    vendor/zte/blade/proprietary/akmd2:system/bin/akmd2 \
    vendor/zte/blade/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/blade/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/blade/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/zte/blade/proprietary/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/zte/blade/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/blade/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/zte/blade/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/zte/blade/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/zte/blade/proprietary/libdll.so:system/lib/libdll.so \
    vendor/zte/blade/proprietary/libcm.so:system/lib/libcm.so \
    vendor/zte/blade/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/blade/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/blade/proprietary/libwms.so:system/lib/libwms.so \
    vendor/zte/blade/proprietary/libnv.so:system/lib/libnv.so \
    vendor/zte/blade/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/blade/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/blade/proprietary/libdss.so:system/lib/libdss.so \
    vendor/zte/blade/proprietary/libauth.so:system/lib/libauth.so \
    vendor/zte/blade/proprietary/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/zte/blade/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/blade/proprietary/libOmxEvrcEnc.so:/system/lib/libOmxEvrcEnc.so \
    vendor/zte/blade/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/zte/blade/proprietary/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/zte/blade/proprietary/libOmxQcelpDec.so:/system/lib/libOmxQcelpDec.so \
    vendor/zte/blade/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/zte/blade/proprietary/libOmxAdpcmDec.so:/system/lib/libOmxAdpcmDec.so \
    vendor/zte/blade/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/zte/blade/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/zte/blade/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/zte/blade/proprietary/libOmxAmrwbDec.so:/system/lib/libOmxAmrwbDec.so \
    vendor/zte/blade/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/zte/blade/proprietary/libOmxQcelp13Enc.so:/system/lib/libOmxQcelp13Enc.so \
    vendor/zte/blade/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/zte/blade/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/zte/blade/proprietary/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/zte/blade/proprietary/libOmxAmrRtpDec.so:/system/lib/libOmxAmrRtpDec.so \
    vendor/zte/blade/proprietary/libOmxAacEnc.so:/system/lib/libOmxAacEnc.so \
    vendor/zte/blade/proprietary/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/blade/proprietary/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/blade/proprietary/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/blade/proprietary/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/blade/proprietary/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/blade/proprietary/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/blade/proprietary/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/zte/blade/proprietary/libloc.so:system/lib/libloc.so \
    vendor/zte/blade/proprietary/libloc.so:obj/lib/libloc.so \
    vendor/zte/blade/proprietary/libloc-rpc.so:system/lib/libloc-rpc.so \
    vendor/zte/blade/proprietary/libcommondefs.so:system/lib/libcommondefs.so

# camera
PRODUCT_COPY_FILES += \
    vendor/zte/blade/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/blade/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/zte/blade/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/blade/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/blade/proprietary/lib/libmm-abl.so:/system/lib/libmm-abl.so \
    vendor/zte/blade/proprietary/lib/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/zte/blade/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/blade/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \

ifeq (1,0)
# added by ioz9 for Camera HAL,from zte offical 2.3.5 ROM
PRODUCT_COPY_FILES += \
    vendor/zte/blade/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/zte/blade/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/zte/blade/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/zte/blade/proprietary/lib/libcameraservice.so:obj/lib/libcameraservice.so \
    vendor/zte/blade/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/zte/blade/proprietary/lib/libcamera_client.so:obj/lib/libcamera_client.so \

endif

ifeq (1,1)
# added by ioz9 for audio eq,from zte offical 2.3.5 ROM
PRODUCT_COPY_FILES += \
    vendor/zte/blade/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/zte/blade/proprietary/lib/libaudioeq.so:/system/lib/libaudioeq.so

# added by ioz9 for soundfx,from zte offical 2.3.5 ROM
PRODUCT_COPY_FILES += \
    vendor/zte/blade/proprietary/lib/soundfx/libbundlewrapper.so:/system/lib/soundfx/libbundlewrapper.so \
    vendor/zte/blade/proprietary/lib/soundfx/libreverbwrapper.so:/system/lib/soundfx/libreverbwrapper.so \
    vendor/zte/blade/proprietary/lib/soundfx/libvisualizer.so:/system/lib/soundfx/libvisualizer.so

# added by ioz9 for opencore,from zte offical 2.3.5 ROM
PRODUCT_COPY_FILES += \
    vendor/zte/blade/proprietary/lib/libopencore_author.so:/system/lib/libopencore_author.so \
    vendor/zte/blade/proprietary/lib/libopencore_common.so:/system/lib/libopencore_common.so \
    vendor/zte/blade/proprietary/lib/libopencore_download.so:/system/lib/libopencore_download.so \
    vendor/zte/blade/proprietary/lib/libopencore_downloadreg.so:/system/lib/libopencore_downloadreg.so \
    vendor/zte/blade/proprietary/lib/libopencorehw.so:/system/lib/libopencorehw.so \
    vendor/zte/blade/proprietary/lib/libopencore_mp4local.so:/system/lib/libopencore_mp4local.so \
    vendor/zte/blade/proprietary/lib/libopencore_mp4localreg.so:/system/lib/libopencore_mp4localreg.so \
    vendor/zte/blade/proprietary/lib/libopencore_net_support.so:/system/lib/libopencore_net_support.so \
    vendor/zte/blade/proprietary/lib/libopencore_player.so:/system/lib/libopencore_player.so \
    vendor/zte/blade/proprietary/lib/libopencore_rtsp.so:/system/lib/libopencore_rtsp.so \
    vendor/zte/blade/proprietary/lib/libopencore_rtspreg.so:/system/lib/libopencore_rtspreg.so \
    vendor/zte/blade/proprietary/lib/libOpenSLES.so:/system/lib/libOpenSLES.so

endif

